version: 0.2
# Version Marker: JS-CircuitBreaker-v3 (Enhanced-Caching-Reporting)
env:
  variables:
    BUILD_CMD: "docker compose build app"
    TEST_CMD: "docker compose run --rm app node evaluation/evaluation.js"
    OUTPUT_DIR: "evaluation"

phases:
  install:
    runtime-versions:
      python: 3.12
      nodejs: 20
    commands:
      - echo "=== INSTALL PHASE ==="
      - docker info >/dev/null 2>&1 || (echo "Docker daemon missing" && touch /tmp/BUILD_FAILED_INSTALL)
  pre_build:
    commands:
      - set +e
      - WORKDIR=${TARGET_DIR:-.}
      - echo "Entering WORKDIR: $WORKDIR"
      - cd "$WORKDIR" || (echo "Failed to enter $WORKDIR" && touch /tmp/BUILD_FAILED_PREBUILD)
      - echo "$(pwd)" > /tmp/actual_workdir
      - mkdir -p evaluation
      - rm -f /tmp/BUILD_FAILED*
  build:
    commands:
      - set +e
      - cd "$(cat /tmp/actual_workdir)"
      - echo "Building Docker image (with cache)..."
      - $BUILD_CMD
      - echo "Running evaluation suite..."
      - $TEST_CMD 2>&1 | tee output.log
      - |
        if [ ${PIPESTATUS[0]} -ne 0 ] || grep -q "❌ Tests failed" output.log; then
          echo "Evaluation failed"
          # We don't touch FAILED_TESTS yet because we want POST_BUILD to try and find the report
        fi
  post_build:
    commands:
      - set +e
      - cd "$(cat /tmp/actual_workdir)"
      - echo "=== POST-BUILD PHASE ==="
      - JOB_ID_VAL="${JOB_ID:-${CODEBUILD_BUILD_ID}}"
      - |
        # Search for report.json anywhere in the project
        REPORT_FILE=$(find . -name "report.json" -type f | head -n 1)
        if [ -n "$REPORT_FILE" ] && [ -n "${REPORT_BUCKET:-}" ]; then
          DEST_KEY="${REPORT_PREFIX:+${REPORT_PREFIX}/}${JOB_ID_VAL}/report.json"
          echo "Uploading $REPORT_FILE to s3://${REPORT_BUCKET}/$DEST_KEY"
          aws s3 cp "$REPORT_FILE" "s3://${REPORT_BUCKET}/$DEST_KEY"
        else
          echo "WARNING: JSON report not found. Files in evaluation/:"
          ls -R evaluation/ || echo "None"
        fi
      - |
        # Fallback to README upload
        README_FILE=$(find . -maxdepth 1 -iname "README.md" | head -n 1)
        if [ -n "$README_FILE" ] && [ -n "${REPORT_BUCKET:-}" ]; then
          DEST_KEY="${REPORT_PREFIX:+${REPORT_PREFIX}/}${JOB_ID_VAL}/README.md"
          aws s3 cp "$README_FILE" "s3://${REPORT_BUCKET}/$DEST_KEY"
        fi
      - |
        if [ -f /tmp/BUILD_FAILED_INSTALL ] || [ -f /tmp/BUILD_FAILED_PREBUILD ]; then
          exit 1
        fi
      - echo "Build process finished."

cache:
  paths:
    - '/root/.npm/**/*'
    - '/root/.cache/pip/**/*'
