version: 0.2
phases:
  build:
    commands:
      - sh y67yp7-go-high-throughput-idempotent-dispatcher/ci_run.sh
artifacts:
  files:
    - y67yp7-go-high-throughput-idempotent-dispatcher/evaluation/report.json
