version: 0.2

phases:
  install:
    commands:
      - echo "Using custom Docker image with Python and Go"
      - go version
      - python3 --version

  pre_build:
    commands:
      - echo "Running repository_before tests"
      - cd $CODEBUILD_SRC_DIR/repository_before
      - go test -v ./...
      - cd $CODEBUILD_SRC_DIR

  build:
    commands:
      - echo "Running Python evaluation"
      - mkdir -p $CODEBUILD_SRC_DIR/evaluation
      - python3 -m evaluation.evaluation --output $CODEBUILD_SRC_DIR/evaluation/report.json

  post_build:
    commands:
      - echo "Running repository_after tests"
      - cd $CODEBUILD_SRC_DIR/repository_after
      - go test -v ./...
      - cd $CODEBUILD_SRC_DIR

artifacts:
  files:
    - evaluation/report.json
