version: 0.2

phases:
  pre_build:
    commands:
      - echo "Pre-build phase - Setting up environment"
      - echo "Build started at $(date)"
      - docker compose build tests test-before

  build:
    commands:
      - echo "Build phase - Running tests"

      # Test repository_before (expected to FAIL)
      - echo "Testing repository_before..."
      - |
        if docker compose run --rm test-before; then
          echo "repository_before tests PASSED (unexpected)"
          export BEFORE_STATUS="PASSED"
        else
          echo "repository_before tests FAILED (expected)"
          export BEFORE_STATUS="FAILED"
        fi

      # Test repository_after (expected to PASS)
      - echo "Testing repository_after..."
      - |
        if docker compose run --rm tests; then
          echo "repository_after tests PASSED"
          export AFTER_STATUS="PASSED"
        else
          echo "repository_after tests FAILED"
          export AFTER_STATUS="FAILED"
          exit 1
        fi

  post_build:
    commands:
      - echo "Post-build phase - Running evaluation"

      # Run evaluation if available
      - |
        if [ -f "evaluation/evaluation.py" ]; then
          echo "Running evaluation script..."
          docker compose run --rm tests bash -c "python evaluation/evaluation.py" || echo "Evaluation script failed (non-critical)"
        fi

      - echo "Build completed at $(date)"
      - echo "repository_before status: $BEFORE_STATUS"
      - echo "repository_after status: $AFTER_STATUS"

      # Exit 0 if repository_after passed, fail otherwise
      - |
        if [ "$AFTER_STATUS" = "PASSED" ]; then
          echo "Build SUCCEEDED - repository_after tests passed"
          exit 0
        else
          echo "Build FAILED - repository_after tests failed"
          exit 1
        fi

artifacts:
  files:
    - '**/*'
  name: spam-detection-demo-artifacts
