version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      docker: 20
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:
      - echo "Preparing environment..."
      - docker -v
  build:
    commands:
      - echo "Running parallel framework tests..."
      - docker-compose run --rm app mvn clean test
  post_build:
    commands:
      - echo "Build completed on `date`"
