version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t hailu3548/jr2pzv-app .
  build:
    commands:
      - echo Running Ground Truth Solution Tests...
      - docker run --rm hailu3548/jr2pzv-app sh -c "cd repository_after && go test -v -race ./..."
  post_build:
    commands:
      - echo Running Evaluation...
      # Mount the evaluation directory to capture the report.json artifact
      - docker run --rm -v $(pwd)/evaluation:/app/evaluation hailu3548/jr2pzv-app python evaluation/evaluation.py
      - echo Build completed on `date`

artifacts:
  files:
    - evaluation/report.json
