version: 0.2

phases:
  build:
    commands:
      - "docker build -t hailu3548/jr2pzv-app ."
      - "docker run --rm hailu3548/jr2pzv-app sh -c 'cd repository_after && go test -v -race ./...'"
  post_build:
    commands:
      - "docker run --rm -v $CODEBUILD_SRC_DIR/y67yp7-go-high-throughput-idempotent-dispatcher/evaluation:/app/evaluation hailu3548/jr2pzv-app python evaluation/evaluation.py"

artifacts:
  files:
    - "evaluation/report.json"
