version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Installing dependencies..."
      - |
        if ! command -v docker-compose &> /dev/null; then
          echo "docker-compose not found, installing..."
          pip install docker-compose
        fi
      - docker --version
      - docker-compose --version
      - |
        if [ $? -ne 0 ]; then
          echo "Docker installation failed"
          touch /tmp/BUILD_FAILED_INSTALL
          exit 1
        fi

  pre_build:
    commands:
      - echo "Pre-build phase..."
      - |
        if ! docker-compose build; then
          echo "Pre-build command failed"
          touch /tmp/BUILD_FAILED_PREBUILD
          exit 1
        fi

  build:
    commands:
      - echo "Build phase..."
      - |
        # Set build commands
        BUILD_CMD_BEFORE="docker-compose run --rm test-before"
        BUILD_CMD_AFTER="docker-compose run --rm test-after"
        BUILD_CMD_EVALUATION="docker-compose run --rm evaluation"
        
        # Run repository_before build command (expected to fail for fix branches)
        echo "Running repository_before build command..."
        /bin/bash -c "set -o pipefail; $BUILD_CMD_BEFORE 2>&1 | tee /tmp/docker_before.log" || echo "Pre-build tests had failures (expected for fix branches, continuing)"
        # Do NOT touch /tmp/BUILD_FAILED_BEFORE on failure - this is expected for fix/refactor branches
        
        # Run repository_after build command (must pass)
        echo "Running repository_after build command..."
        if ! /bin/bash -c "set -o pipefail; $BUILD_CMD_AFTER 2>&1 | tee /tmp/docker_after.log"; then
          echo "Post-build command failed"
          touch /tmp/BUILD_FAILED_AFTER
          exit 1
        fi
        
        # Run evaluation (must pass)
        echo "Running evaluation..."
        if ! /bin/bash -c "set -o pipefail; $BUILD_CMD_EVALUATION 2>&1 | tee /tmp/docker_evaluation.log"; then
          echo "Evaluation command failed"
          touch /tmp/BUILD_FAILED_TESTS
          exit 1
        fi

  post_build:
    commands:
      - echo "Post-build phase..."
      - |
        # Check for critical build failures (excluding BEFORE which is expected to fail for fix branches)
        if [ -f /tmp/BUILD_FAILED_INSTALL ] || [ -f /tmp/BUILD_FAILED_PREBUILD ] || [ -f /tmp/BUILD_FAILED_AFTER ] || [ -f /tmp/BUILD_FAILED_TESTS ]; then
          echo "FATAL: One or more critical build steps failed. Exiting with error."
          exit 1
        fi
        echo "Build completed successfully. Before tests may have failed (expected for fix branches), but after tests and evaluation passed."

artifacts:
  files:
    - 'evaluation/reports/**/*'
    - 'tests/*_results.json'
    - 'README.md'
  name: build-artifacts
