version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "=== INSTALL PHASE ==="
      - if ! docker info >/dev/null 2>&1; then
          echo "Docker daemon not available — ensure CodeBuild project has privilegedMode=true"
          touch /tmp/BUILD_FAILED_INSTALL
        fi
      
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo "$DOCKER_TOKEN" | docker login --username "$DOCKER_USER" --password-stdin
      - |
        WORKDIR=${TARGET_DIR:-.}
        # Try to enter directory
        if ! cd "$WORKDIR"; then
          echo "WARNING: Unable to enter target directory ${WORKDIR}"
          touch /tmp/BUILD_FAILED_PREBUILD
        fi
        
        # FIX 1: Persist the absolute path for later phases
        PWD=$(pwd)
        echo "$PWD" > /tmp/build_dir
        echo "Persisted working directory: $PWD"
        
        if ! mkdir -p "${OUTPUT_DIR}"; then
          echo "WARNING: Unable to create output directory ${OUTPUT_DIR}"
          touch /tmp/BUILD_FAILED_PREBUILD
        fi
        rm -f /tmp/BUILD_FAILED* /tmp/*.log || true

  build:
    commands:
      - |
        # FIX 1: Reload the absolute path from pre_build
        if [ -f /tmp/build_dir ]; then
          cd "$(cat /tmp/build_dir)"
        else
          cd "${TARGET_DIR:-.}"
        fi
        
        # FIX 2: Use bash explicitly with pipefail to handle piping + exit codes
        # instead of unsupported ${PIPESTATUS} in the default shell.
        
        # 1. PRE-BUILD COMMAND
        if [ -n "${BUILD_CMD_BEFORE:-}" ]; then
          echo "Running repository_before build command..."
          # We use single quotes for the outer bash command so $BUILD_CMD_BEFORE is expanded safely inside
          if ! /bin/bash -c "set -o pipefail; $BUILD_CMD_BEFORE 2>&1 | tee /tmp/docker_before.log"; then
              echo "Pre-build command failed"
              touch /tmp/BUILD_FAILED_BEFORE
          fi
        fi
        
        # 2. POST-BUILD COMMAND
        echo "Running repository_after build command..."
        if ! /bin/bash -c "set -o pipefail; $BUILD_CMD_AFTER 2>&1 | tee /tmp/docker_after.log"; then
            echo "Post-build command failed"
            touch /tmp/BUILD_FAILED_AFTER
        fi
        
        # 3. TEST COMMAND
        echo "Running tests/report command..."
        if ! /bin/bash -c "set -o pipefail; $TEST_CMD 2>&1 | tee /tmp/tests.log"; then
            echo "Test command failed"
            touch /tmp/BUILD_FAILED_TESTS
        fi

  post_build:
    commands:
      - |
        # FIX 1: Reload the absolute path
        if [ -f /tmp/build_dir ]; then
          cd "$(cat /tmp/build_dir)"
        else
          cd "${TARGET_DIR:-.}"
        fi
        
        echo "=== POST-BUILD PHASE ==="
        
        KEY_PREFIX=$(echo "${REPORT_PREFIX:-}" | sed 's#^/*##;s#/*$##')
        JOB_ID_VAL="${JOB_ID:-${CODEBUILD_BUILD_ID}}"
        
        upload_s3() {
          local src=$1
          local dest_key=$2
          if [ -n "${REPORT_BUCKET:-}" ] && [ -f "$src" ] && command -v aws >/dev/null 2>&1; then
             echo "Uploading $src to s3://${REPORT_BUCKET}/$dest_key"
             aws s3 cp "$src" "s3://${REPORT_BUCKET}/$dest_key" || echo "WARNING: Upload failed for $src"
          fi
        }
        
        # Detect and Upload Report
        find_latest_report() {
          OUTPUT_DIR=${OUTPUT_DIR:-.}
          
          [ -d "$OUTPUT_DIR" ] || return 1
          
          find -L "$OUTPUT_DIR" -type f -name '*.json' -print 2>/dev/null | head -n 1
        }
        
        REPORT_FILE=$(find_latest_report)
        
        if [ -n "$REPORT_FILE" ]; then
           REPORT_KEY="${KEY_PREFIX:+${KEY_PREFIX}/}${JOB_ID_VAL}/report.json"
           upload_s3 "$REPORT_FILE" "$REPORT_KEY"
        else
          echo "WARNING: JSON report not found under $OUTPUT_DIR"
          echo "FILES FOUND: $(ls -1 $OUTPUT_DIR 2>/dev/null || echo 'None')"
        fi
        
        README_FILE=$(ls -1 README.md README.MD README Readme.md 2>/dev/null | head -n 1 || true)
        if [ -n "$README_FILE" ]; then
           README_KEY="${KEY_PREFIX:+${KEY_PREFIX}/}${JOB_ID_VAL}/README.md"
           upload_s3 "$README_FILE" "$README_KEY"
        else
          echo "NOTE: README file not found"
        fi
        
        echo "=== POST-BUILD PHASE COMPLETE ==="
        
        if [ -f /tmp/BUILD_FAILED_INSTALL ] || [ -f /tmp/BUILD_FAILED_PREBUILD ] || [ -f /tmp/BUILD_FAILED_BEFORE ] || [ -f /tmp/BUILD_FAILED_AFTER ] || [ -f /tmp/BUILD_FAILED_TESTS ]; then
          echo "FATAL: One or more build steps failed. Exiting with error."
          exit 1
        fi

# Default environment variables
env:
  OUTPUT_DIR: evaluation
  REPORT_PREFIX: codebuild-reports
