version: 0.2

phases:
  pre_build:
    commands:
      - echo "Building Docker image..."
      - docker-compose build
  build:
    commands:
      - echo "Running tests for repository_before (expected failures)..."
      - docker-compose run --rm test_before || true
      - echo "Running tests for repository_after (expected all pass)..."
      - docker-compose run --rm test_after
      - echo "Running evaluation..."
      - docker-compose run --rm evaluation
  post_build:
    commands:
      - echo "Build completed successfully - test_before failures are expected"
      - rm -f /tmp/BUILD_FAILED_BEFORE || true
      - echo "Cleaned up failure flags - build succeeded"
